### ISSUE TITLE
how to deal with the white background and white character

### ISSUE THREAD

**Issue by wanghaisheng** [openpaperwork/libpillowfight#5] opened 2017-05-11 11:28 UTC
![02old](https://cloud.githubusercontent.com/assets/2363295/25946951/db73f7a6-367f-11e7-8237-a59dd40f1ad6.jpg)
i attach an example file , is there any best practise .what i want is to get the character and then OCR them

**Comment by jflesch** [comment] 2017-05-11 13:04
Looks like a captcha. This one is really tricky :-)

I doubt there is any real best practice. The only thing you can do is find pre-processing methods that make the text obvious enough for OCR on most of your images.

I've tested some methods quickly, and up to now, I've found only one that works.

Basically here, the problem is that the text color is really close to the background color. I think your best bet is to make the text as obvious as possible to OCR by switching to pure black & white. The main problem here is to find the best threshold.

Assuming all your images are similar, figuring out the best threshold is something you can brute-force easily:
```py
import PIL.Image
import pyocr

ocr = pyocr.get_available_tools()[0]

img = PIL.Image.open("test_image.jpeg")
img = img.rotate(90)
img = img.resize((img.size[0] * 8, img.size[1] * 8), PIL.Image.RASTERIZE)  # bigger is better
gray = img.convert('L')

for threshold in range(0, 255):
    bw = gray.point(lambda x: 0 if x < threshold else 255, '1')
    txt = ocr.image_to_string(bw, lang='eng')
    print ("{}: {}".format(i, txt)
```

From the output, you can see the best threshold for your image is about ~233.

Unfortunately, even with the correct image threshold, Tesseract cannot guess the image orientation correctly. There is too little text in the image for it to give a reliable answer.

And even with the correct orientation, this image remains really tricky:
- the '5' are cut (missing piece in the middle). And 5 are often easily mistaken with S
- the 'S' are written with a nasty font, making them easy to mistake for '5'.
- the last '4' looks really close to a '1'. Tesseract is going to assume that the differences with a '4' are mistakes and ignore them. A human brain knows better.
- A word dictionary cannot be used here to correct mistakes.

To fix all these "mistakes", you can try [training Tesseract](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract) like you would do for a new language (however there is nothing in Pyocr to make the training). I wouldn't be surprised if Tesseract 4 would work really well on these images with a specific training.

You may want to have a look at [PWNtcha](http://caca.zoy.org/wiki/PWNtcha). I think it's really close to what you're trying to achieve here.

Since you've opened this ticket on libpillowfight, I assume you wonder if SWT could help. It can't. SWT is designed to extract text from natural scenes (for instance, text on signs in photos). SWT looks for large strokes ("Stroke Width"). I think the strokes on your images are by far too narrow.

Anyway, since this ticket is not actually related to libpillowfight, I'm going to close it. But feel free to comment on it again if you want to continue this discussion :-)

**Closed by jflesch** 2017-05-11 13:04 UTC

**Comment by wanghaisheng** [comment] 2017-05-12 03:20
somehow  i combine methods this lib provided ,as following ,work perfect well
```
import pillowfight

import PIL.Image
import sys

import pyocr
import pyocr.builders
img_in = PIL.Image.open("02.old.bmp")

# step01 ace
ace_out_img = pillowfight.ace(img_in,
	slope=10,
	limit=1000,
	samples=100,
	seed=None)


# step 02 
sobel_out_img = pillowfight.sobel(img_in)
ocr = pyocr.get_available_tools()[0]
txt = ocr.image_to_string(out_img, lang='eng')
print('截取后预处理识别:'+txt)
```

**Comment by jflesch** [comment] 2017-05-12 15:16
Hm yes, the Sobel filter is a good idea. I'm actually surprised Tesseract has been able to read the '4' :-)

**Comment by jflesch** [comment] 2017-05-12 15:19
BTW, if you need performance, I suggest you have a look at OpenCV.

Libpillowfight is designed to be as simple as possible and require as little dependencies as possible, so it uses only the CPU, and I'm fairly certain it could be optimized a lot.
AFAIK, OpenCV is able to use GPUs for this kind of computations, and I assume it also provides a Sobel filter implementation. For big images, it could speed up things a lot for you.

**Comment by wanghaisheng** [comment] 2017-05-12 16:07
@jflesch   actually  every time tesseract may give me a different answer (tesseract 3.04)
get that , it seems what really matters is the ace and sobel method , let me dig  opencv a little.
thx for your advice  .
