### ISSUE TITLE
Badly needed unpappers deskew algorithms (pls add this filter)

### ISSUE THREAD

**Issue by junaedahmed** [openpaperwork/libpillowfight#8] opened 2017-10-04 12:42 UTC
For tabular data extraction before feeding the image to the ocr it needs to be deskewed for accurate column detection. Pls add this filter to truely python based wrapping for image processing purpose.

**Comment by jflesch** [comment] 2017-10-04 12:45
Duplicate of #4.
However, quite frankly, I doubt I will have the required time to work on it before long, sorry. If you do have the time, feel free to send a patch.

**Closed by jflesch** 2017-10-04 12:45 UTC
